// <auto-generated />
using System;
using KonkursCheck.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KonkursCheck.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260514173738_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KonkursCheck.Domain.Entities.BankruptcySummary", b =>
                {
                    b.Property<string>("PersonCvrId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("person_cvr_id");

                    b.Property<string[]>("CompanyNames")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("company_names");

                    b.Property<DateTime>("LastCalculated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_calculated");

                    b.Property<DateOnly?>("MostRecentDate")
                        .HasColumnType("date")
                        .HasColumnName("most_recent_date");

                    b.Property<int>("TotalBankruptcies")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("total_bankruptcies");

                    b.HasKey("PersonCvrId");

                    b.HasIndex("TotalBankruptcies")
                        .IsDescending()
                        .HasDatabaseName("idx_summary_bankruptcies");

                    b.ToTable("bankruptcy_summaries", (string)null);
                });

            modelBuilder.Entity("KonkursCheck.Domain.Entities.Company", b =>
                {
                    b.Property<string>("CvrNumber")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("cvr_number");

                    b.Property<DateOnly?>("BankruptcyDate")
                        .HasColumnType("date")
                        .HasColumnName("bankruptcy_date");

                    b.Property<DateOnly?>("DissolutionDate")
                        .HasColumnType("date")
                        .HasColumnName("dissolution_date");

                    b.Property<DateOnly?>("FoundedDate")
                        .HasColumnType("date")
                        .HasColumnName("founded_date");

                    b.Property<string>("IndustryCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("industry_code");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("CvrNumber");

                    b.HasIndex("Name")
                        .HasDatabaseName("idx_companies_name");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Name"), "GIN");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Name"), new[] { "gin_trgm_ops" });

                    b.ToTable("companies", (string)null);
                });

            modelBuilder.Entity("KonkursCheck.Domain.Entities.Person", b =>
                {
                    b.Property<string>("PersonCvrId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("person_cvr_id");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("full_name");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated");

                    b.HasKey("PersonCvrId");

                    b.HasIndex("FullName")
                        .HasDatabaseName("idx_persons_name");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("FullName"), "GIN");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("FullName"), new[] { "gin_trgm_ops" });

                    b.ToTable("persons", (string)null);
                });

            modelBuilder.Entity("KonkursCheck.Domain.Entities.PersonCompanyRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("CvrNumber")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("cvr_number");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("PersonCvrId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("person_cvr_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.HasKey("Id");

                    b.HasIndex("CvrNumber")
                        .HasDatabaseName("idx_roles_company");

                    b.HasIndex("PersonCvrId")
                        .HasDatabaseName("idx_roles_person");

                    b.ToTable("person_company_roles", (string)null);
                });

            modelBuilder.Entity("KonkursCheck.Domain.Entities.BankruptcySummary", b =>
                {
                    b.HasOne("KonkursCheck.Domain.Entities.Person", "Person")
                        .WithOne("BankruptcySummary")
                        .HasForeignKey("KonkursCheck.Domain.Entities.BankruptcySummary", "PersonCvrId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("KonkursCheck.Domain.Entities.PersonCompanyRole", b =>
                {
                    b.HasOne("KonkursCheck.Domain.Entities.Company", "Company")
                        .WithMany("PersonRoles")
                        .HasForeignKey("CvrNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KonkursCheck.Domain.Entities.Person", "Person")
                        .WithMany("Roles")
                        .HasForeignKey("PersonCvrId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("KonkursCheck.Domain.Entities.Company", b =>
                {
                    b.Navigation("PersonRoles");
                });

            modelBuilder.Entity("KonkursCheck.Domain.Entities.Person", b =>
                {
                    b.Navigation("BankruptcySummary");

                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
